### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by newge** [ctpbee/ctpbee_api#2]

**Comment by newge** [comment]
发现了一个细节问题，在安装 ctpbee_api 时 pip 默认会选择 0.19 版本，0.2 版本的会被忽略掉，从[ Release history ](https://pypi.org/project/ctpbee_api/#history) 页面显示在最下面，采用命名 0.20 可能有效。0.2 版本我这边安装也会出现上面错误

**Comment by somewheve** [comment]
问题 来自于 mainfest.in 没有包含package的数据   现在已经修复并准备提交了
