### ISSUE TITLE
关于替换成期货公司指定的api版本请大佬提供帮助

### ISSUE THREAD

**Issue by myougg** [ctpbee/ctpbee_api#4]
我需要成期货公司指定的版本(api版本：v6.6.1_P1_CP_20210406 8:37:47)，下载地址：https://www.founderfu.com/fzzqqh_2019/technology_407.html，
现在的ctpbee_api\ctp\vnctp工程代码由于我安装的是build tool版本，不能打开sln文件，能提供一个cmake能编译的版本吗，谢谢了！！

**Comment by somewheve** [comment]
推荐使用6.3.16 版本的 仿真穿透接口  将include/ctp/ 四个头文件进行替换 然后 然后将  `thostmduserapi_se.dll`  以及 `thostmduserapi_se.lib`  和 `thosttraderapi_se.dll` 和 `thosttraderapi_se.lib` （for windows） linux则替换.so 文件  然后 python setup.py build  进行编译 没啥问题 就pip install .

**Comment by myougg** [comment]
上期官网评测版本最低是6.3.19，用6.3.19可以吗

**Comment by somewheve** [comment]
可以试下 都是向前兼容的
